
== url-shortener

Simple demonstration code base to create an URL shorterner API.

=== Prerequisites

You can user either Leiningen (version >= 2.9) or Docker (any recent version should wor) to run this project on your local machine

=== Running using Leiningen

To start a web server for the application, run:

....
lein ring server
....

Then the web server is available at http://localhost:3000 (the browser should be openend automatically when the command is run)

=== Running using Docker

To start the web server using Docker, run:

....
docker build -t url-short .
docker run -it --rm --name url-short -v /var/run/docker.sock:/var/run/docker.sock -p 3000:3000 url-short
....

Then the web server is available at http://localhost:3000

== Caveats

This is not a proper implementation. Here is a list of some elements that could be improved (non exhaustive list):

- No database connection pool
- Optimistic locking not implemented
- No API documentation (eg OpenAPI)
- No unit test
- No production artifact (only dev is done)
- Deleting row should be logical. Right now, it is really deleted.
- Dockerfile could be optimized, eg the an uberjar could be generated and run using `java`
- A lot of error management is missing, everywhere: results from the database, paremeters check in all functions, parameters sent by the client in HTTP endpoints...

== Current implementation

Is is using simple libraries: ring and compojure. It is basic and simple for the requirements of this project.

Testcontainers is used to create a Postgres database using Docker when the app is started.

A few layers: `handler.clj` for dealing with HTTP endpoints, `service.clj` for having a simple layer service and `database.clj` for database accesses.

3 endpoints:
- POST `/short` with a parameter named `url` in a JSON body: Creation a short URL based on the URL sent in the body
- GET ``/:short_url`` : convert the `short_url` provided in the path to a full URL
- DELETE `/url` with either a parameter named `long_url` or `hash` in a JSON body: deleting a registered short URL either using the hash or the long URL
